### ISSUE TITLE
fix: compatibility with node v18

### ISSUE THREAD

**Issue by eamon0989** [s1seven/schema-tools#205]
# Description

Running `npm run build` throws an error in `schema-tools-generate-en10168-pdf-template` and `schema-tools-generate-coa-pdf-template`

```
 ✖  nx run @s1seven/schema-tools-generate-coa-pdf-template:build
       > @s1seven/schema-tools-generate-coa-pdf-template@0.5.1 build
       > PARCEL_WORKER_BACKEND=process parcel build --no-cache --target=main
       
       Error: No native build was found for platform=darwin arch=arm64 runtime=node abi=108 uv=1 armv=8 libc=glibc node=18.13.0
           loaded from: /Users/eamon/work/schema-tools/packages/generate-coa-pdf-template/node_modules/lmdb
       
           at load.path (/Users/eamon/work/schema-tools/packages/generate-coa-pdf-template/node_modules/node-gyp-build/index.js:59:9)
           at load (/Users/eamon/work/schema-tools/packages/generate-coa-pdf-template/node_modules/node-gyp-build/index.js:21:30)
           at Object.<anonymous> (/Users/eamon/work/schema-tools/packages/generate-coa-pdf-template/node_modules/lmdb/dist/index.cjs:2250:47)
           at Module._compile (/Users/eamon/work/schema-tools/packages/generate-coa-pdf-template/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
           at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
           at Module.load (node:internal/modules/cjs/loader:1081:32)
           at Module._load (node:internal/modules/cjs/loader:922:12)
           at Module.require (node:internal/modules/cjs/loader:1105:19)
           at require (/Users/eamon/work/schema-tools/packages/generate-coa-pdf-template/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
           at _lmdb (/Users/eamon/work/schema-tools/packages/generate-coa-pdf-template/node_modules/@parcel/cache/lib/LMDBCache.js:51:39)
       

    ✖  nx run @s1seven/schema-tools-generate-en10168-pdf-template:build
       > @s1seven/schema-tools-generate-en10168-pdf-template@0.7.1 build
       > PARCEL_WORKER_BACKEND=process parcel build './src/generateContent.ts' --no-cache --target=main
       
       Error: No native build was found for platform=darwin arch=arm64 runtime=node abi=108 uv=1 armv=8 libc=glibc node=18.13.0
           loaded from: /Users/eamon/work/schema-tools/packages/generate-en10168-pdf-template/node_modules/lmdb
       
           at load.path (/Users/eamon/work/schema-tools/packages/generate-en10168-pdf-template/node_modules/node-gyp-build/index.js:59:9)
           at load (/Users/eamon/work/schema-tools/packages/generate-en10168-pdf-template/node_modules/node-gyp-build/index.js:21:30)
           at Object.<anonymous> (/Users/eamon/work/schema-tools/packages/generate-en10168-pdf-template/node_modules/lmdb/dist/index.cjs:2250:47)
           at Module._compile (/Users/eamon/work/schema-tools/packages/generate-en10168-pdf-template/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
           at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
           at Module.load (node:internal/modules/cjs/loader:1081:32)
           at Module._load (node:internal/modules/cjs/loader:922:12)
           at Module.require (node:internal/modules/cjs/loader:1105:19)
           at require (/Users/eamon/work/schema-tools/packages/generate-en10168-pdf-template/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
           at _lmdb (/Users/eamon/work/schema-tools/packages/generate-en10168-pdf-template/node_modules/@parcel/cache/lib/LMDBCache.js:51:39)
```

**What keywords did you search in schema-tools issues before filing this one ?**

**Is this a BUG REPORT or FEATURE REQUEST ?**

BUG REPORT

**Environment :**

local, mac

**What you expected to happen :**

I expected the build to complete successfully

Running

**How to reproduce it :**

Use node v18 and run `npm run build`.
Switching to v16 gets rid of the error.

**Comment by getlarge** [comment]
Did you try to reinstall all dependencies then rebuild ?
